# Generated by Django 3.1.1 on 2020-09-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='desciprtion',
            new_name='description',
        ),
    ]
